import ProductCardWidget4 from "../ProductCardWidget4";
import ProductCardBuilder from "../ProductCardBuilder";
import ProductCardWidget2 from "../ProductCardWidget2";
import ProductDisplayWidget3 from "../ProductDisplayWidget3";

function ProductCardDisplay({
  shouldRenderComponent5,
  shouldRenderComponent3,
  shouldRenderComponent1,
  renderComponentOrImage1,
  renderComponentOrText3,
  renderAdditionalContent1,
  renderAdditionalContent3,
  renderComponentOrText1,
  shouldApplyDiscount1,
  imgContent14,
  imgContent19,
  imgContent24,
  imgContent29,
  imgContent13,
  imgContent18,
  imgContent23,
  imgContent28,
  imgContent16,
  imgContent21,
  imgContent26,
  imgContent31,
  productPrice3,
  productPrice1,
  productPriceText1,
  productCountOrDescription1,
  productDescriptionCount1,
  productCountIdentifier1,
  productDescriptionCount3,
  productDescription5,
  renderContentBasedOnCondition3,
  productDescription7,
  renderContentBasedOnCondition1,
  determinePriceDisplayStyle1,
  productDescription8,
  productDescription9,
  productDescriptionTitle1,
  productDescriptionOrTitle3,
  productPriceRange1,
  productPriceDiscounted1,
  containerWidthConstraint3,
  containerWidthOrMinWidth1,
  containerWidthStyle1,
  containerWidthSpecifier1,
  containerWidthConstraint7,
  containerWidthConstraints1,
  containerWidthConstraint5,
  containerWidthConstraint1,
  imgHeight4,
  imgHeight3,
  imgHeight5,
  dynamicPaddingAmount1,
  dynamicPaddingSpacing1,
  calculatePaddingDistance1,
  dynamicPaddingAmount3,
  paddingRightValue3,
  paddingRightValue1,
}) {
  return (
    <div className="flex justify-between items-center flex-row gap-4 w-[100.00%] box-border first:mt-0 mt-[16.00px]">
      <ProductCardWidget4
        shouldRenderComponent5={false}
        renderComponentOrText3={false}
        imgContent14={imgContent14}
        imgContent13={imgContent13}
        imgContent16={imgContent16}
        productPrice3={productPrice3}
        productCountOrDescription1={productCountOrDescription1}
        productDescription5={productDescription5}
        productDescription8={productDescription8}
        containerWidthConstraint3={containerWidthConstraint3}
        containerWidthConstraint7={containerWidthConstraint7}
        dynamicPaddingAmount1={dynamicPaddingAmount1}
        dynamicPaddingAmount3={dynamicPaddingAmount3}
      />
      <ProductCardBuilder
        shouldRenderComponent3={false}
        renderAdditionalContent1={false}
        imgContent19={imgContent19}
        imgContent18={imgContent18}
        imgContent21={imgContent21}
        productPrice1={productPrice1}
        productDescriptionCount1={productDescriptionCount1}
        renderContentBasedOnCondition3={renderContentBasedOnCondition3}
        productDescription9={productDescription9}
        containerWidthOrMinWidth1={containerWidthOrMinWidth1}
        containerWidthConstraints1={containerWidthConstraints1}
        imgHeight3={imgHeight3}
        dynamicPaddingSpacing1={dynamicPaddingSpacing1}
        paddingRightValue3={paddingRightValue3}
      />
      <ProductCardWidget2
        shouldRenderComponent1={false}
        renderAdditionalContent3={false}
        imgContent24={imgContent24}
        imgContent23={imgContent23}
        imgContent26={imgContent26}
        productPriceText1={productPriceText1}
        productCountIdentifier1={productCountIdentifier1}
        productDescription7={productDescription7}
        productDescriptionTitle1={productDescriptionTitle1}
        containerWidthStyle1={containerWidthStyle1}
        containerWidthConstraint5={containerWidthConstraint5}
        imgHeight4={imgHeight4}
        calculatePaddingDistance1={calculatePaddingDistance1}
        paddingRightValue1={paddingRightValue1}
      />
      <ProductDisplayWidget3
        renderComponentOrImage1={false}
        renderComponentOrText1={false}
        shouldApplyDiscount1={false}
        imgContent29={imgContent29}
        imgContent28={imgContent28}
        imgContent31={imgContent31}
        productDescriptionCount3={productDescriptionCount3}
        renderContentBasedOnCondition1={renderContentBasedOnCondition1}
        determinePriceDisplayStyle1={determinePriceDisplayStyle1}
        productDescriptionOrTitle3={productDescriptionOrTitle3}
        productPriceRange1={productPriceRange1}
        productPriceDiscounted1={productPriceDiscounted1}
        containerWidthSpecifier1={containerWidthSpecifier1}
        containerWidthConstraint1={containerWidthConstraint1}
        imgHeight5={imgHeight5}
      />
    </div>
  );
}

export default ProductCardDisplay;
